branches:
  only:
    - master
    - v14

language: android
jdk: oraclejdk7
android:
  components:
    - tools
    - platform-tools
    - extra-android-support
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
    - android-22
    - build-tools-22.0.0
  licenses:
        - '.+'

before_install:
 - chmod +x gradlew

install:
  - ./gradlew dependencies

script:
  - ./gradlew build
