branches:
  only:
    - master

language: android
jdk: oraclejdk7
android:
  components:
    - tools
    - platform-tools
    - extra-android-support
    - extra-android-m2repository
    - extra-google-google_play_services
    - android-22
    - build-tools-22.0.0

before_install:
 - chmod +x gradlew

install:
  - ./gradlew dependencies

script:
  - ./gradlew build
