branches:
  only:
    - master

language: android
android:
  components:
    - tools
    - platform-tools
    - extra-android-support
    - extra-android-m2repository
    - android-20
    - build-tools-20.0.0

install:
  - ./gradlew dependencies

script:
  - ./gradlew build

after_success:
  - ./gradlew uploadArchives